### ISSUE TITLE
two-way-sync lagging studio sometimes

### ISSUE THREAD

**Issue by rullinoiz** [Roblox/rojo#344]
the output fills up with write responses when i type one character, and over in vscode i just see characters being placed and removed really fast

![image](https://user-images.githubusercontent.com/46585763/87818217-1203c600-c81f-11ea-8185-89fe8fd28830.png)

**Comment by LPGhatguy** [comment]
Two way sync is _incredibly_ unstable; this is one of the issues that pops up! Because it's so early on, we're not supporting use of the feature yet, and it's likely not quite ready for bug reports.

This is roughly a duplicate of #295.

**Comment by rullinoiz** [comment]
> Two way sync is _incredibly_ unstable; this is one of the issues that pops up! Because it's so early on, we're not supporting use of the feature yet, and it's likely not quite ready for bug reports.
> 
> This is roughly a duplicate of #295.

ah, ok. thanks for the notice
