### ISSUE TITLE
[CRITICAL?] Syncing localization tables no longer works after latest Roblox update

### ISSUE THREAD

**Issue by Jaguar-515** [Roblox/rojo#351]
https://devforum.roblox.com/t/release-notes-for-445/743262/4

This could have affected everyone's workflows when using .csv files for syncing.

**Comment by Jaguar-515** [comment]
https://github.com/Roblox/rojo/pull/352#issuecomment-681180138

Once this PR is merged, I'll go ahead and close this.

**Comment by howmanysmall** [comment]
You can close it. It was rolled back.
